services:

  app:
    hostname: hbm-dev-20.it.helsinki.fi
    container_name: brain-and-mind-app
    image: druidfi/drupal-web:php-8.1
    volumes:
      - .:/app:delegated
      - drupal_public_files:/app/public/sites/default/files
    environment:
      APP_ENV: test
      DRUPAL_ROUTES: https://hbm-dev-20.it.helsinki.fi
      DRUSH_OPTIONS_URI: https://hbm-dev-20.it.helsinki.fi
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -S mailhog:1025 -t -i
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.entrypoints: https
      traefik.http.routers.nginx.rule: Host(`hbm-dev-20.it.helsinki.fi`)
      traefik.http.routers.nginx.tls: "true"
      traefik.http.routers.nginx.priority: 1
      traefik.docker.network: hbm-network
    logging:
      driver: "journald"
      options:
        tag: "HBM-NGINX"
    networks:
      - hbm-network
      - default

  mailhog:
    container_name: brain-and-mind-mailhog
    image: druidfi/mailhog:latest
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.mailhog.entrypoints: https
      traefik.http.routers.mailhog.rule: Host(`hbm-dev-20.it.helsinki.fi`) && PathPrefix(`/mailhog`)
      traefik.http.routers.mailhog.tls: "true"
      traefik.http.routers.mailhog.priority: 2
      traefik.http.services.mailhog.loadbalancer.server.port: 8025
      traefik.docker.network: hbm-network
    environment:
      MH_UI_WEB_PATH: mailhog
    networks:
      - hbm-network
      - default

  db:
    container_name: brain-and-mind-db
    image: druidfi/mariadb:10.11-drupal-lts
    volumes:
      - drupal_db_data:/var/lib/mysql
    restart: unless-stopped
    logging:
      driver: "journald"
      options:
        tag: "HBM-DB"
    networks:
      - hbm-network
      - default

volumes:
  drupal_db_data:
    external: true
  drupal_public_files:
    external: true

networks:
  hbm-network:
    external: true
