services:

  app:
    hostname: research.helsinkibrainandmind.fi
    container_name: brain-and-mind-app
    image: brain-and-mind-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - drupal_public_files:/app/public/sites/default/files
    environment:
      APP_ENV: prod
      DRUPAL_ROUTES: https://research.helsinkibrainandmind.fi
      DRUSH_OPTIONS_URI: https://research.helsinkibrainandmind.fi
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -S smtp.helsinki.fi:25 -t -i
    restart: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.entrypoints: https
      traefik.http.routers.nginx.rule: Host(`research.helsinkibrainandmind.fi`)
      traefik.http.routers.nginx.tls: "true"
      traefik.docker.network: hbm-network
    logging:
      driver: "journald"
      options:
        tag: "HBM-NGINX"
    networks:
      - hbm-network
      - default

  db:
    container_name: brain-and-mind-db
    image: druidfi/mariadb:10.11-drupal-lts
    volumes:
      - drupal_db_data:/var/lib/mysql
    restart: unless-stopped
    logging:
      driver: "journald"
      options:
        tag: "HBM-DB"
    networks:
      - hbm-network
      - default

volumes:
  drupal_db_data:
    external: true
  drupal_public_files:
    external: true

networks:
  hbm-network:
    external: true
