<?php

/**
 * @file
 * Contains installation procedures.
 */

/**
 * Mismatched entity and/or field definitions.
 * The field_industrial_collaboration field needs to be updated.
 */
function bnm_content_update_8201() {
  $entity_definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $field_storage_definition = $entity_definition_update_manager->getFieldStorageDefinition('field_industrial_collaboration', 'node');
  $entity_definition_update_manager->updateFieldStorageDefinition($field_storage_definition);
}
